<?php
// Error Codes
define('ERROR_NOT_REPO_OWNER', 'ERROR_NOT_REPO_OWNER');
define('ERROR_FORKED_REPO', 'ERROR_FORKED_REPO');
define('ERROR_INVALID_CREDENTIALS', 'ERROR_INVALID_CREDENTIALS');
define('ERROR_NO_TAGS', 'ERROR_NO_TAGS');
define('ERROR_UNKNOWN_TAG', 'ERROR_UNKNOWN_TAG');
define('ERROR_NO_PLUGIN', 'ERROR_NO_PLUGIN');
define('ERROR_MISC_SYSTEM', 'ERROR_MISC_SYSTEM');
define('ERROR_MISSING_PACKAGE_FILE', 'ERROR_MISSING_PACKAGE_FILE');
?>
