<?php
define('ERROR_NOT_REPO_OWNER', 'ERROR_NOT_REPO_OWNER');
define('ERROR_FORKED_REPO', 'ERROR_FORKED_REPO');
define('ERROR_INVALID_CREDENTIALS', 'ERROR_INVALID_CREDENTIALS');
define('ERROR_NO_TAGS', 'ERROR_NO_TAGS');
define('ERROR_UNKNOWN_TAG', 'ERROR_UNKNOWN_TAG');
?>
